language:
  - c

sudo:
  - false

os:
  - linux
  - osx

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew bundle; fi

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - ctest --output-on-failure

